### ISSUE TITLE
Is this activley developed?

### ISSUE THREAD

**Issue by xanathon** [digital-dream-labs/vector-web-setup#22]
The last commit is a week old. Is this even actively developed?

**Comment by kercre123** [comment]
I don't think this tool is their top priority, imo. They only have a few devs and I bet their main priority is escape pod and/or OSKR. Right now there are a few bugs here and there, but there is nothing that really needs active attention especially after earlier commits. Nothing has been pushed to npm yet though....

**Comment by xanathon** [comment]
I see this as a highly unfinished app that does not do what is advertised. You actually can not push a firmware to a non-dev robot for it to stay there (even if the documentation says otherwise). And they advertise it as an alternative to the Android and iOS apps, but it is by far inferior to those when it comes to settings - so this goal also was not met (and we have not talked about the fact that less tech-compatible people will not be able to use this at all - this again shows in my opinion that most developers have no clues on how few things "normal" users actually are able to do).

To me it looks like DDL just released something highly unfinished to give the impression they are actually working on something after they botched the "firm date" (their words) for Escape Pod on july 15th.

I suggested months ago to setup an open accessible Kanban board that shows what they are actually working on at the moment, but so far DDL prefers intransparency.

I had high hopes when this Github repository was released as I saw it as a step in the right direction when it comes to professionally and transparently informing the backers, but from the look of it I was wrong.

**Comment by kercre123** [comment]
This looks near finished to me. I'd count this as an alternative to the app. Alternatives don't have to do every single thing the original does. This tool was an Anki developed tool (no way they could have developed all of this in that short time), and they put their branding on it. It was designed to setup bots with a relatively intuitive interface, provide an easy way to manage firmware, and that is it. Nothing really says otherwise. The firmware will auto update if you try to run older VicOS, but it isn't meant for downgrading. It does all of the functions it says it does (at least for me). It will be a great way for putting on OSKR/Escape Pod OTAs.

OSKR/Escape Pod will probably take quite long since those are tools they have to develop entirely by themselves.

The tool isn't perfect. There are some missing assets and stuff but a lot of the actual issues seem to involve Web Bluetooth.

DDL has done some questionable things, but I have faith.

**Comment by grant-olson** [comment]
Progress can be tracked on the [milestone page](https://github.com/digital-dream-labs/vector-web-setup/milestones) as well as looking at the [pull request page](https://github.com/digital-dream-labs/vector-web-setup/pulls) . As with any open source project pull requests will receive more prompt attention than issues.

For a completely functional and independent software stack where users can control versions of software installed, etc, we still need to finish the Escape Pod and generate updated software for Vector itself. This will allow users to control automatic updates on their own and that's where we're focusing our attention now. Still it seemed worth releasing individual components as we can so users can see that we are making progress towards are ultimate goal and begin to look under the hood at the code.
